# Generated by Django 5.1.6 on 2025-02-20 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_sender', '0002_uploadedfile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='image',
        ),
    ]
